### ISSUE TITLE
Netty+MQTT 服务端是如何实现SSL/TLS？

### ISSUE THREAD

**Issue by wangzengjing** [xjc-opensource/ext-opensource-netty#1]
最近想写一个netty+mqtt服务端的实现，要实现安全性要用到ssl/tls，请问有什么例子吗？

**Comment by xjc-opensource** [comment]
源码里已有示例了,
/ext.opensource.netty-server-example/src/main/java/ext/opensource/netty/server/example/MqttServerApplication.java

**Comment by wangzengjing** [comment]
好的，谢谢
